name = "myweb-receipt-scanner"
main = "src/worker.js"
compatibility_date = "2026-05-17"
workers_dev = true
preview_urls = true

[[kv_namespaces]]
binding = "INVOICES"
id = "a22ddbe5d50843e5a5fc2de04084df29"
preview_id = "df01f1893a524d5b8de9d3308f6e98a3"
